# Generated by Django 4.2.5 on 2023-09-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonModel', '0002_alter_financialdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
